# Generated by Django 4.1.2 on 2022-10-15 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_hotel_stars'),
        ('tours', '0008_travel_price'),
        ('profiles', '0002_mybooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MyTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.travel')),
            ],
        ),
        migrations.DeleteModel(
            name='MyBooking',
        ),
    ]
