# Generated by Django 4.1.2 on 2022-10-15 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_room_empty'),
        ('profiles', '0003_myhotel_mytravel_delete_mybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhotel',
            name='rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.room'),
        ),
    ]
