# Generated by Django 4.1.1 on 2022-10-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='hotelrank',
            name='stars_num',
        ),
        migrations.AddField(
            model_name='hotelrank',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel'),
        ),
    ]
