# Generated by Django 4.1.1 on 2022-10-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_rank_remove_hotelrank_stars_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.FloatField(null=True),
        ),
    ]
