# Generated by Django 4.1.2 on 2022-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_roomcategory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
