# Generated by Django 4.1.2 on 2022-10-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_roomcategory_check_in_roomcategory_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
