# Generated by Django 4.1.2 on 2022-10-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_roomcategory_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
