# Generated by Django 4.1.2 on 2022-10-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_room_remove_hotel_room_category_delete_roomcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='hotels'),
        ),
    ]
