# Generated by Django 4.1.2 on 2022-10-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='empty',
            field=models.BooleanField(default=False),
        ),
    ]
