# Generated by Django 4.1.1 on 2022-10-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_room_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_cat', to='hotels.hotelcategory'),
        ),
    ]
