# Generated by Django 4.1.2 on 2022-10-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='lacotion',
            new_name='location',
        ),
    ]
