# Generated by Django 4.1.2 on 2022-10-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_rename_lacotion_travel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='stars',
            field=models.IntegerField(default=3),
        ),
    ]
