# Generated by Django 4.1.2 on 2022-10-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_travel_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='rank',
        ),
    ]
