# Generated by Django 4.1.2 on 2022-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_travel_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTourDestinationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='traveltourdestination',
            name='image',
        ),
        migrations.AddField(
            model_name='traveltourdestination',
            name='images',
            field=models.ManyToManyField(null=True, to='tours.traveltourdestinationimages'),
        ),
    ]
