# Generated by Django 4.1.2 on 2022-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_traveltourdestinationimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltourdestination',
            name='images',
            field=models.ManyToManyField(to='tours.traveltourdestinationimages'),
        ),
    ]
