# Generated by Django 4.1.2 on 2022-10-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_traveltourdestination_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
