# Generated by Django 4.1.1 on 2022-10-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=211)),
                ('phone', models.CharField(max_length=211)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=211)),
                ('message', models.TextField()),
            ],
        ),
    ]
